#!/bin/bash

OUTPUT=$(until sudo apt update; do sleep 15; done)
STATUS=$(echo $OUTPUT | grep -c "All packages are up to date")
if [ $STATUS -eq 0 ]; then
    sudo apt upgrade -y
    sudo apt autoremove -y
    systemctl reboot -i
fi
